### ISSUE TITLE
How to import SASS stylesheet?

### ISSUE THREAD

**Issue by mattbrun** [dmapper/d-draggable-table#1]
Hi guys,
I hope the question is not too silly...

I'm trying to use this component, but I cannot import the style since I use Stylus and the component style is in SASS.
Since I couldn't find a SASS compiler for derby in the repos, I thought derby handles SASS natively, but looking [here](https://github.com/derbyjs/derby/blob/master/lib/App.server.js#L22) doesn't seem so.
In fact, trying to add

```
app.loadStyles(path.join(__dirname, '..', '..', 'node_modules', 'd-draggable-table', 'index.sass'));
```

in my app `index.js`, i receive this error

``` bash
/home/user1/Sync/work/dev/cows/node_modules/derby/lib/files.js:123
    throw new Error('Unable to find compiler for: ' + extension);
          ^
Error: Unable to find compiler for: .sass
  at Object.loadStylesSync (/home/user1/Sync/work/dev/cows/node_modules/derby/lib/files.js:123:11)
  at App._loadStyles (/home/user1/Sync/work/dev/cows/node_modules/derby/lib/App.server.js:211:22)
  at App.loadStyles (/home/user1/Sync/work/dev/cows/node_modules/derby/lib/App.server.js:203:8)
  at Object.<anonymous> (/home/user1/Sync/work/dev/cows/apps/admin/index.js:32:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/user1/Sync/work/dev/cows/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /home/user1/Sync/work/dev/cows/server.js:40:5
  at Racer.Derby.run (/home/user1/Sync/work/dev/cows/node_modules/derby/lib/Derby.server.js:17:5)
  at Object.<anonymous> (/home/user1/Sync/work/dev/cows/server.js:32:7)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:929:3
```

Thanks,
MB

**Comment by ovvn** [comment]
Hi, I've added styles folder. This is how I make an import in my app's styling config:

```
@import '../../../../node_modules/d-draggable-table/styles/index.styl'
```

And this is how I require needed component in the app's index: 

```
app.component require('d-draggable-table/components/sortable-table')
app.component require('d-draggable-table')
```

**Comment by mattbrun** [comment]
It works great now, thanks :)
